### ISSUE TITLE
Discussion around testing options with xolvio:cucumber as an option

### ISSUE THREAD

**Issue by rhyslbw** [CodeAdventure/space-pioneer#3]
I'm a little short on time right now but need to start implementing some end to end tests, so I'm hoping you can clear up some confusion right now. My understanding is this package (utilising Pioneer) and [xolvio:cucumber](https://github.com/xolvio/meteor-cucumber) are essentially providing a nicer interface to the [js cucumber](https://github.com/cucumber/cucumber-js) implementation, purpose fit for Meteor. If that's the case, what's the difference between the two packages?

**Comment by DominikGuzei** [comment]
Hey @rhyslbw, yes you are right!
I wrote this package, because 9 months ago when I started implementing end-to-end tests all the other velocity packages didn't work very well for me. Sam (who wrote xolvio:cucumber) and I are currently thinking about merging our efforts into his package because he already did a better integration with velocity and Meteor. Our plan is to build something similar (but better) to pioneer.js widgets because we all like the concept :wink: 

So I think it would be better to start with xolvio:cucumber, so you can benefit from future development!

**Comment by rhyslbw** [comment]
Great, really glad to hear about the possible merge!
